
title: My Resume
url: 'http://dohxis.github.io'
baseurl: ''

style: styles-4

name: Domantas MauruÄa
tagline: Backend Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

email: dohxis@gmail.com
github: dohxis
twitter: '@dohxis'
